[package]
name = "study-query-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
arrow = { version = "54.1.0", features = ["prettyprint"] }
arrow-schema = "54.1.0"
derive_builder = "0.20.2"
thiserror = "2.0.11"
